"""model call accounting (AS-024)

Deferred from AS-005 on purpose: the schema there covers what S0 and S1 consume, and
writing this table before the provider existed would have guaranteed rewriting it once
the shape of a model call was actually known.


Revision ID: 59da5103fe01
Revises: 7693ac6961d8
Create Date: 2026-09-06 16:03:15.185673

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59da5103fe01"
down_revision: str | Sequence[str] | None = "7693ac6961d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_calls",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("requested_model", sa.String(length=128), nullable=False),
        sa.Column("purpose", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("prompt_registry_hash", sa.String(length=64), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("stop_reason", sa.String(length=64), nullable=True),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("schema_valid", sa.Boolean(), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cost_usd >= 0", name=op.f("ck_model_calls_model_call_cost_is_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_model_calls_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_calls")),
    )
    op.create_index(op.f("ix_model_calls_created_at"), "model_calls", ["created_at"], unique=False)
    op.create_index(op.f("ix_model_calls_model"), "model_calls", ["model"], unique=False)
    op.create_index(op.f("ix_model_calls_provider"), "model_calls", ["provider"], unique=False)
    op.create_index(op.f("ix_model_calls_run_id"), "model_calls", ["run_id"], unique=False)
    op.create_index(
        "ix_model_calls_run_purpose", "model_calls", ["run_id", "purpose"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_model_calls_run_purpose", table_name="model_calls")
    op.drop_index(op.f("ix_model_calls_run_id"), table_name="model_calls")
    op.drop_index(op.f("ix_model_calls_provider"), table_name="model_calls")
    op.drop_index(op.f("ix_model_calls_model"), table_name="model_calls")
    op.drop_index(op.f("ix_model_calls_created_at"), table_name="model_calls")
    op.drop_table("model_calls")
    # ### end Alembic commands ###
