"""initial control plane schema

Revision ID: 7693ac6961d8
Revises:
Create Date: 2026-08-31 22:57:11.626530

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7693ac6961d8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("workflow_id", sa.String(length=255), nullable=True),
        sa.Column("action_digest", sa.String(length=64), nullable=True),
        sa.Column("principal", sa.String(length=255), nullable=True),
        sa.Column("tool", sa.String(length=128), nullable=True),
        sa.Column(
            "trust_label",
            sa.Enum(
                "TRUSTED",
                "UNTRUSTED",
                "MODEL_GENERATED",
                name="trust_label",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_action_digest"), "audit_events", ["action_digest"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_run_id"), "audit_events", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_workflow_id"), "audit_events", ["workflow_id"], unique=False
    )
    op.create_table(
        "capability_jti_uses",
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column(
            "redeemed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operation_id", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("jti", name=op.f("pk_capability_jti_uses")),
    )
    op.create_index(
        op.f("ix_capability_jti_uses_operation_id"),
        "capability_jti_uses",
        ["operation_id"],
        unique=False,
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("workflow_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "PREPARING",
                "COLLECTING_CONTEXT",
                "PLANNING",
                "AUTHORIZING",
                "WAITING_APPROVAL",
                "EXECUTING",
                "VALIDATING",
                "REPORTING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "DENIED_EXPIRED",
                name="run_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("principal", sa.String(length=255), nullable=False),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("repository", sa.String(length=512), nullable=True),
        sa.Column("control_profile", sa.String(length=64), nullable=True),
        sa.Column("planner_kind", sa.String(length=32), nullable=True),
        sa.Column("policy_bundle_hash", sa.String(length=64), nullable=True),
        sa.Column("tool_registry_hash", sa.String(length=64), nullable=True),
        sa.Column("prompt_registry_hash", sa.String(length=64), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "config_snapshot",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("workflow_id", name=op.f("uq_runs_workflow_id")),
    )
    op.create_index(op.f("ix_runs_control_profile"), "runs", ["control_profile"], unique=False)
    op.create_index(op.f("ix_runs_created_at"), "runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_runs_planner_kind"), "runs", ["planner_kind"], unique=False)
    op.create_table(
        "action_attempts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("action_digest", sa.String(length=64), nullable=False),
        sa.Column("plan_step_occurrence", sa.Integer(), nullable=False),
        sa.Column("tool", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=128), nullable=False),
        sa.Column("resource", sa.String(length=512), nullable=False),
        sa.Column(
            "arguments",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "preconditions",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "EXECUTED",
                "DENIED_POLICY",
                "DENIED_NO_CAPABILITY",
                "DENIED_CAPABILITY_EXPIRED",
                "DENIED_CAPABILITY_REPLAYED",
                "DENIED_DIGEST_MISMATCH",
                "DENIED_APPROVAL_MISSING",
                "DENIED_APPROVAL_EXPIRED",
                "DENIED_UNKNOWN_TOOL",
                "DENIED_INVALID_ARGUMENTS",
                "DENIED_PRECONDITION_CHANGED",
                "FAILED_BACKEND",
                name="attempt_outcome",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("denial_reason", sa.String(length=255), nullable=True),
        sa.Column("was_executed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT was_executed OR outcome = 'EXECUTED'",
            name=op.f("ck_action_attempts_executed_flag_matches_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_action_attempts_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_attempts")),
    )
    op.create_index(
        op.f("ix_action_attempts_action_digest"), "action_attempts", ["action_digest"], unique=False
    )
    op.create_index(
        op.f("ix_action_attempts_created_at"), "action_attempts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_action_attempts_outcome"), "action_attempts", ["outcome"], unique=False
    )
    op.create_index(
        "ix_action_attempts_run_digest",
        "action_attempts",
        ["run_id", "action_digest"],
        unique=False,
    )
    op.create_index(op.f("ix_action_attempts_run_id"), "action_attempts", ["run_id"], unique=False)
    op.create_index(op.f("ix_action_attempts_tool"), "action_attempts", ["tool"], unique=False)
    op.create_index(
        op.f("ix_action_attempts_was_executed"), "action_attempts", ["was_executed"], unique=False
    )
    op.create_table(
        "action_plans",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "steps",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("planner_kind", sa.String(length=32), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_action_plans_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_plans")),
        sa.UniqueConstraint("run_id", "sequence", name=op.f("uq_action_plans_run_id_sequence")),
    )
    op.create_index(
        op.f("ix_action_plans_created_at"), "action_plans", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_action_plans_run_id"), "action_plans", ["run_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("action_digest", sa.String(length=64), nullable=False),
        sa.Column("approval_context_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "DENIED",
                "EXPIRED",
                name="approval_state",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("approver_principal", sa.String(length=255), nullable=True),
        sa.Column(
            "evidence_refs",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'PENDING') OR (approver_principal IS NOT NULL) OR (state = 'EXPIRED')",
            name=op.f("ck_approvals_decided_approval_has_an_approver"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_approvals_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(
        op.f("ix_approvals_action_digest"), "approvals", ["action_digest"], unique=False
    )
    op.create_index(op.f("ix_approvals_created_at"), "approvals", ["created_at"], unique=False)
    op.create_index(op.f("ix_approvals_expires_at"), "approvals", ["expires_at"], unique=False)
    op.create_index(op.f("ix_approvals_run_id"), "approvals", ["run_id"], unique=False)
    op.create_table(
        "execution_ledger",
        sa.Column("operation_id", sa.String(length=255), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("workflow_id", sa.String(length=255), nullable=False),
        sa.Column("action_digest", sa.String(length=64), nullable=False),
        sa.Column("plan_step_occurrence", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "FAILED",
                name="execution_state",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("external_ref", sa.String(length=512), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_execution_ledger_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("operation_id", name=op.f("pk_execution_ledger")),
    )
    op.create_index(
        op.f("ix_execution_ledger_action_digest"),
        "execution_ledger",
        ["action_digest"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_ledger_created_at"), "execution_ledger", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_execution_ledger_run_id"), "execution_ledger", ["run_id"], unique=False
    )
    op.create_index(
        "ix_execution_ledger_workflow_digest",
        "execution_ledger",
        ["workflow_id", "action_digest"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_ledger_workflow_id"), "execution_ledger", ["workflow_id"], unique=False
    )
    op.create_table(
        "policy_decisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("action_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "ALLOW",
                "DENY",
                "REQUIRE_APPROVAL",
                name="policy_outcome",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column(
            "obligations",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("policy_bundle_hash", sa.String(length=64), nullable=True),
        sa.Column("engine_latency_ms", sa.Float(), nullable=True),
        sa.Column("fail_closed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_policy_decisions_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_decisions")),
    )
    op.create_index(
        op.f("ix_policy_decisions_action_digest"),
        "policy_decisions",
        ["action_digest"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_decisions_created_at"), "policy_decisions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_policy_decisions_outcome"), "policy_decisions", ["outcome"], unique=False
    )
    op.create_index(
        op.f("ix_policy_decisions_run_id"), "policy_decisions", ["run_id"], unique=False
    )
    op.create_table(
        "capability_grants",
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("approval_id", sa.String(length=64), nullable=True),
        sa.Column("action_digest", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("audience", sa.String(length=255), nullable=False),
        sa.Column("environment", sa.String(length=64), nullable=False),
        sa.Column("tool", sa.String(length=128), nullable=False),
        sa.Column("resource", sa.String(length=512), nullable=False),
        sa.Column(
            "scopes",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("key_id", sa.String(length=64), nullable=False),
        sa.Column("registry_hash", sa.String(length=64), nullable=True),
        sa.Column("policy_bundle_hash", sa.String(length=64), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
            name=op.f("fk_capability_grants_approval_id_approvals"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_capability_grants_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("jti", name=op.f("pk_capability_grants")),
    )
    op.create_index(
        op.f("ix_capability_grants_action_digest"),
        "capability_grants",
        ["action_digest"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capability_grants_created_at"), "capability_grants", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_capability_grants_expires_at"), "capability_grants", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_capability_grants_run_id"), "capability_grants", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_capability_grants_run_id"), table_name="capability_grants")
    op.drop_index(op.f("ix_capability_grants_expires_at"), table_name="capability_grants")
    op.drop_index(op.f("ix_capability_grants_created_at"), table_name="capability_grants")
    op.drop_index(op.f("ix_capability_grants_action_digest"), table_name="capability_grants")
    op.drop_table("capability_grants")
    op.drop_index(op.f("ix_policy_decisions_run_id"), table_name="policy_decisions")
    op.drop_index(op.f("ix_policy_decisions_outcome"), table_name="policy_decisions")
    op.drop_index(op.f("ix_policy_decisions_created_at"), table_name="policy_decisions")
    op.drop_index(op.f("ix_policy_decisions_action_digest"), table_name="policy_decisions")
    op.drop_table("policy_decisions")
    op.drop_index(op.f("ix_execution_ledger_workflow_id"), table_name="execution_ledger")
    op.drop_index("ix_execution_ledger_workflow_digest", table_name="execution_ledger")
    op.drop_index(op.f("ix_execution_ledger_run_id"), table_name="execution_ledger")
    op.drop_index(op.f("ix_execution_ledger_created_at"), table_name="execution_ledger")
    op.drop_index(op.f("ix_execution_ledger_action_digest"), table_name="execution_ledger")
    op.drop_table("execution_ledger")
    op.drop_index(op.f("ix_approvals_run_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_expires_at"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_created_at"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_action_digest"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_action_plans_run_id"), table_name="action_plans")
    op.drop_index(op.f("ix_action_plans_created_at"), table_name="action_plans")
    op.drop_table("action_plans")
    op.drop_index(op.f("ix_action_attempts_was_executed"), table_name="action_attempts")
    op.drop_index(op.f("ix_action_attempts_tool"), table_name="action_attempts")
    op.drop_index(op.f("ix_action_attempts_run_id"), table_name="action_attempts")
    op.drop_index("ix_action_attempts_run_digest", table_name="action_attempts")
    op.drop_index(op.f("ix_action_attempts_outcome"), table_name="action_attempts")
    op.drop_index(op.f("ix_action_attempts_created_at"), table_name="action_attempts")
    op.drop_index(op.f("ix_action_attempts_action_digest"), table_name="action_attempts")
    op.drop_table("action_attempts")
    op.drop_index(op.f("ix_runs_planner_kind"), table_name="runs")
    op.drop_index(op.f("ix_runs_created_at"), table_name="runs")
    op.drop_index(op.f("ix_runs_control_profile"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_capability_jti_uses_operation_id"), table_name="capability_jti_uses")
    op.drop_table("capability_jti_uses")
    op.drop_index(op.f("ix_audit_events_workflow_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_run_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action_digest"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
